config/routes.rb
Rails.application.routes.draw do
  resources :courses do
    resources :examinations do
      resources :scores, only: [:index]
      patch 'scores/edit', to: 'scores#update' 
    end
    resources :students, except: [:show]
  end

  devise_for :users, skip: :all

  # if user authenticated then root is courses page
  authenticated :user do
    root 'courses#index', as: :authenticated_root
  end

  #Change default devise routes
  devise_scope :user do
    get 'sign_in', to: 'devise/sessions#new', as: :new_user_session
    post 'sign_in', to: 'devise/sessions#create', as: :user_session
    delete 'sign_out', to: 'devise/sessions#destroy', as: :destroy_user_session
    root to: redirect('/sign_in')
  end

  patch 'set_locale', to: 'locale#set_locale'
  match "/404", :to => "errors#not_found", :via => :all, :as => :not_found
  match "/500", :to => "errors#internal_server_error", :via => :all

end

app/views/layouts/_card.html.erb
<div class="card-form <% if xl %> xl <% end %>">
  <div class="card">
    <div class="card-body">
      <h5 class="bold"><%= t(title) %></h5> 
      <hr>
        <%= yield :form %>
    </div>
  </div>
</div>

app/views/layouts/_contentCard.html.erb
<div class="card card-table">
  <div class="container card-body">
    <%= yield :back %>
    <h1><%= card_title.capitalize %></h1>
    <h5><%= yield :subtitle %></h5>
    <hr>
    <% if collection.try(:empty?) %>
      <%= yield :no_results %>
    <% else %>
        <div class="card-btns">
            <%= yield :btns %>
        </div>
        <% if content_for?(:form) %>
          <%= yield :form %>
        <% else %>
          <div class="table-responsive">
              <%= yield :table %>
          </div>
        <% end %>
        <% if !collection.nil? && !collection.empty? %>
            <div class="float-right">
            <%= paginate collection.page %>
            </div>
        <% end %>
      <% end %> 
    </div>
  </div>  

app/views/layouts/_footer.html.erb
<footer>
    <div class="container">
        <div class="row">
            <div class="col col-md-5">
                <p><i class="fa fa-at"></i> Trabajo Final Integrador - TTPS Ruby 2017 </p>
            </div>
            <div class="col col-md-7">
                <ul class="socials">
                    <li><i class="fa fa-user" data-toggle="tooltip" data-placement="top" title="Franco Martin Borrelli"></i></li>
                </ul>
            </div>
        </div>
    </div>
</footer>

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 4.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
  <div class="alertContainer">
    <div class="alert alert-dismissable center-block fade show alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>" role="alert">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  </div>
  <% end %>
<% end %>

app/views/layouts/_modal.html.erb
<div class="modal fade" tabindex="-1" role="dialog" id="delete-confirm">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title"><%= t(title) %></h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <p><%= t(del_msg) %></p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn" data-dismiss="modal"><%=t(:cancel)%></button>
        <%= link_to t(:delete), route_path + '/pony', method: :delete, :class => 'btn btn-danger' %>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar fixed-top navbar-expand-sm navbar-light">
 <button class="navbar-toggler navbar-toggler-left" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
    <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
      <ul class="navbar-nav mt-2 mt-md-0 ml-auto">
        <li class="nav-item dropdown ml-auto">
          <%= render "layouts/navigation_links" %>
          <% if user_signed_in? %>
              <a class="nav-link dropdown-toggle" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <%= current_user.username %>
              </a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                <% if @home.nil? %>
                  <%= link_to courses_path, class: "dropdown-item" do %>
                    <i class="fa fa-graduation-cap" aria-hidden="true"></i> <%= (t :course).pluralize.capitalize %>
                  <% end %>
                  <div class="dropdown-divider"></div>
                <% end %>
                <%= link_to destroy_user_session_path,  method: :delete, class: "dropdown-item" do %>
                  <i class="fa fa-sign-out" aria-hidden="true"></i>  <%= t :signOut %>
                <% end %>
              </div>
          <% else %>
                <%= link_to t(:home), "/", class: "nav-link" %>
            <% end %>
        </li>        
      </ul>
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>

<li class="nav-item">
    <% if I18n.locale == I18n.default_locale %>
        <%= link_to "English", set_locale_path(:language => "en"), :method => 'patch', class: "nav-link" %>
    <% else %>
        <%= link_to "Español", set_locale_path(:language => "es-AR"), :method => 'patch', class: "nav-link" %>
    <%end%>
</li>

app/views/layouts/_no_results.html.erb
    <div class="no-results">
        <div class="content">
            <h3><%= t title %></h3>
            <i class="fa fa-<%= icon %>" aria-hidden="true"></i>
            <br>
            <%= link_to t(text), path, class: "btn btn-outline-primary" %>
        </div>
    </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Ruby - #{(t :course).capitalize.pluralize}" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "App" %>">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => 'reload' %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <main role="main">
      <%= yield :modal %>
      <div class="content">
              <%= render 'layouts/messages' %>
        <div class = "container body">
        <%= yield %>
        </div>
      </div>
    </main>
    <%= render 'layouts/footer' %>
  </body>
</html>